<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>BotML</string>
    <key>scopeName</key>
    <string>source.botml</string>
    <key>fileTypes</key>
    <array>
      <string>.bot</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>Specification = starts with !</string>
        <key>match</key>
        <string>^!.*$\n?</string>
        <key>name</key>
        <string>markup.heading.specification.block.bot</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Comments - starts with #</string>
        <key>match</key>
        <string>^(#).*$</string>
        <key>name</key>
        <string>comment.block.bot</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.bot</string>
          </dict>
        </dict>
      </dict>
      <!--
      <dict>
        <key>comment</key>
        <string>Interceptors</string>
        <key>name</key>
        <string>strong.header.bot</string>
        <key>match</key>
        <string>^\s*>\s.+$</string>
      </dict>
      -->
      <dict>
        <key>comment</key>
        <string>Output</string>
        <key>name</key>
        <string>variable.selector.bot</string>
        <key>match</key>
        <string>^\s*<</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Variables</string>
        <key>name</key>
        <string>variable.interpolation.bot</string>
        <key>match</key>
        <string>[\$#\*]\{\w+\}</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Variables</string>
        <key>name</key>
        <string>variable.interpolation.bot</string>
        <key>match</key>
        <string>\$\w*</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Workflow</string>
        <key>begin</key>
        <string>^\s*~</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>entity.name.tag.bot</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Reference</string>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>name</key>
        <string>string.quoted.single.bot</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>List</string>
        <key>begin</key>
        <string>^\s*=</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>markup.bold.bot</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>List</string>
        <key>match</key>
        <string>^(-)\s+</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>markup.bold.bot</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Service</string>
        <key>match</key>
        <string>^\s*(@)\s*(\w+)\s+([^\s]+)\s*$</string>
        <key>captures</key>
        <array>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.bold.bot</string>
            </dict>
          </dict>
          <dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>markup.bold.bot</string>
            </dict>
          </dict>
          <dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>meta.definition.variable.bot</string>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Service</string>
        <key>match</key>
        <string>^\s*(@)\s*(?:(\w+)\(\$\)\s*(\.[\w\.\[\]\d]*)?$)?</string>
        <key>captures</key>
        <array>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.bold.bot</string>
            </dict>
          </dict>
          <dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>markup.bold.bot</string>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Dialogue</string>
        <key>match</key>
        <string>^\s*([<>])\s*</string>
        <key>name</key>
        <string>entity.name.function.bot</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Prompt</string>
        <key>match</key>
        <string>^\s*(\?)\s*</string>
        <key>name</key>
        <string>entity.name.function.bot</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Regular expression</string>
        <key>match</key>
        <string>/.+/</string>
        <key>name</key>
        <string>string.regexp.bot</string>
      </dict>
    </array>
  </dict>
</plist>
